run:
	npm start
css:
	npm run generate-css
replb:
	npm run repl:browser
repln:
	npm run repl:node
clean:
	npm run clean
reset:
	npm run reset
reset-all:
	npm run reset:all
test:
	npm test
build:
	npm run build
deps:
	npm install

.PHONY: run css replb repln clean reset reset-all test build deps
